F test_login_pytest.py::test_func
 def test_func():
 >       assert func(3) == 5
 E       assert 4 == 5
 E        +  where 4 = func(3)
 
 test_login_pytest.py:6: AssertionError
